### ISSUE TITLE
python3.9 missing for Rolling on Ubuntu jammy

### ISSUE THREAD

**Issue by JanStaschulat** [osrf/infrastructure#11]
- [x] I have checked [ROS Answers](https://answers.ros.org) for similar reports and solutions.
- [x] I have checked the [ROS Status page](https://status.ros.org) and my issue is not listed there.
- [x] I have checked the [open issues](https://github.com/osrf/infrastructure/issues) for similar reports.
- [x] This is **not** a [security issue](https://github.com/osrf/infrastructure/blob/latest/SECURITY.md) If you have a security issue to report please do so via email to <security@openrobotics.org>.

## Problem description
I read this [related issue at ROS Answers](https://answers.ros.org/question/397215/no-rule-to-make-libpython-when-using-rosidl_generate_interfaces-dependencies), however, I don't know how to update this dependency on ROS 2 build farm when building rclc for Rolling on Ubuntu jammy. E.g.:

https://build.ros2.org/job/Rpr__rclc__ubuntu_jammy_amd64/23/console

```
11:53:04 --- stderr: rclc
11:53:04 gmake[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libpython3.9.so', needed by 'librclc.so'.  Stop.
11:53:04 gmake[1]: *** [CMakeFiles/Makefile2:140: CMakeFiles/rclc.dir/all] Error 2
11:53:04 gmake: *** [Makefile:149: all] Error 2
11:53:04 ---
```

After having installed python3.9 in our [Github Action](https://github.com/ros2/rclc/pull/266/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f), the `rti_connext_dds_cmake_module` is missing some dependency. See [this comment](https://github.com/ros2/rclc/issues/266#issuecomment-1069003213_).

**Comment by clalancette** [comment]
Yes, this is currently an issue across the board for the ROS 2 Rolling packages.  Ubuntu 22.04 is in the midst of a transition from Python 3.9 to Python 3.10.  Half of the packages we need to build are built for 3.9, and half for 3.10, so we can't build a complete set.  At the moment we are waiting for Ubuntu to rebuild all of the packages we need, so there isn't a whole lot we can do at the moment.

**Comment by nuclearsandwich** [comment]
Ubuntu has completed the transition. There are a few low-level packages which hard-code the python3 version in their bloom patches which need a re-release and we'll start the Rolling rebuild with those today.

**Comment by JanStaschulat** [comment]
@nuclearsandwich thanks for the update. 
Re-running the build job on Open Robotics build farm: is successful.

**Comment by nuclearsandwich** [comment]
With the [Rolling sync out](https://discourse.ros.org/t/new-packages-for-ros-2-rolling-ridley-2022-03-24/24830) I think we can close this issue.
