### ISSUE TITLE
The formatting of every page on wiki.ros.org is bad

### ISSUE THREAD

**Issue by mjs973** [osrf/infrastructure#19]
- [x] I have checked [Robotics StackExchange](https://robotics.stackexchange.com/) for similar reports and solutions.
- [x] I have checked the [Open Robotics Status page](https://status.openrobotics.org) and my issue is not listed there.
- [x] I have checked the [open issues](https://github.com/osrf/infrastructure/issues) for similar reports.
- [x] This is **not** a [security issue](https://github.com/osrf/infrastructure/blob/latest/SECURITY.md) If you have a security issue to report please do so via email to <security@openrobotics.org>.

## Problem description

The formatting of every page on https://wiki.ros.org/ is messed up, as if someone deleted critical files from a template. Also, many image files are missing (but not all.)

**Comment by nuclearsandwich** [comment]
Thanks for the report. We're in the process of updating the web host which powers the wiki and the static content responsible for styling wasn't fully configured.

The static content should now be resolved and pages are rendering as they were before for me. Please re-open this issue if the problem persists after forcing a refresh (back in the day browsers weren't meant to cache 404s but I honestly have no idea what they do now)
