### ISSUE TITLE
ROS Answers sort-of broken due to spam protection (?)

### ISSUE THREAD

**Issue by gavanderhoorn** [osrf/infrastructure#6]
This is basically a cross-post (yes, I know) of https://github.com/ros-infrastructure/answers.ros.org/issues/213, to give it some more visibility.

Not sure whether this will help (being the weekend and all), but it seems more-and-more people are running into issues with Akismet (or at least: I assume it's Akismet having been enabled).

**Comment by tfoote** [comment]
The akismet enabling has been disabled. So we're back to still having issues with profile spammers that get caught in our moderation queue. That should bring is back to operational for most users.
