### ISSUE TITLE
ROS Q&A internal server error

### ISSUE THREAD

**Issue by mjs973** [osrf/infrastructure#7]
When I try to read the body of a question on answers.ros.org. many (but not all) show the message "Internal server error". This has been happening since it came back from yesterday's down time.

For example, this one:
https://answers.ros.org/question/384644/setting-environmental-variables-in-code/

https://status.ros.org/ claims everything is fine.

**Comment by tfoote** [comment]
This might have been a startup issue. It seems to be working now.

![Screenshot from 2021-09-21 10-26-27](https://user-images.githubusercontent.com/447804/134218568-2933d90d-3385-4193-aaec-719c6566658a.png)
