### ISSUE TITLE
https on snapshot repository serves incorrect (?) certificate?

### ISSUE THREAD

**Issue by gavanderhoorn** [osrf/infrastructure#8]
Navigating to https://snapshots.ros.org results in a warning telling me the certificate served is invalid for that specific host.

Seems it's for `cloudfront.net` and `*.cloudfront.net`.

Being able to use HTTPS for apt downloads would be nice.

**Comment by tfoote** [comment]
Please just use the http urls. We haven't setup https for any of our primary package hosting. The repository is gpg signed so the encryption is not an issue for securely delivering the content. See the Debian explanation: https://wiki.debian.org/SecureApt

The encryption prevents many of the standard tools used for more efficient mass content distribution such as caches, mirrors, and transparent proxies. https is explicitly designed to prevent a man in the middle but it makes our ability to deliver the content more expensive both in computational overhead and network overhead.
